language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "HXKUwozdlJVGmzPOrJvi+TwfM5+WCNnF/J1dqT75YR4NUj6akp74yCRPbmW46aK4SSWLJjTMvbuAA7fsUm2Ho41k/E/Ou1kFkG91nrAvX4cg/6n9+ntfufMvKl1XpJdR0MwWtaww9vegvYyEJPdKlE9zfnN1ZGtOKUXYCZRlP1E="
    - secure: "Ee2lJsZx+SepVikgBpTogLbJJ6F6J2XrwV8DQZaH7APY3zVW5BMLfxrcTw77kLAqo/4jOybAYlWrT6PQmSDn5Xx8u1CAV56RxkHRFGcmcbo6pJ55p3Pgl148XfgGXHnOET7nmNoDCyADjWxoPdp4wmEcb+M476ARx+W075N5b8g="

before_install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh
  - ../graphwalker-project/tools/build.sh

install:
  - mvn -q deploy --settings ../graphwalker-project/deploy.xml
