language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "gMeB2EAcM48W6g+vzeh8Tf0Aeld3FN810hem4fRXrCxy01yQ8cJWPCTXG7Sh3UH73Zyllpd2q0nOLv74vgZ9HIDLOmVDIScNsrp5vD3HCCPDwUgcWO+LypjhJTJe2VX/HohrAuXXWDYDp685cgZMmZxjv7JnV1OoPIi1pVWcWIM="
    - secure: "XTP3Y6A5e/W9+TGpyL/jMDroHbrX5tCaNaeTxxZ05/p6PfjHr7fbw76LAmnYNhIF2Y1lpXnmMuaX9ONZASx/PiOtdBT2ZUpM+EnN+CDMhxVfsO41j94Eu2I6i6xyhFtryhAawiavfbe48p7F1iwi2J98Nbu1eKwVd/x5rz6yOOw="

before_install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh
  - ../graphwalker-project/tools/build.sh

install:
  - mvn -q deploy --settings ../graphwalker-project/deploy.xml