language: java
jdk:
- openjdk7
branches:
  only:
  - master
env:
  global:
  - secure: Si+FksmD04Qev09hkYqWYN4rYQderrvMt6/kZBTgEek/v4Bd8QVCcbkZemYQCLnfhm94fNJDVrvpbrZhkeSWhCXKnnsYMH9oaxQWSd4aUI55V9QAseVAWMod5d2TSD7kTIo1owV5xh9LHTLmwnv4v6WmV3dSHSQc0zQh09dFC/M=
  - secure: IVcJyf13GCwLkpYKqygwTH9f3EG1YiqdmXWPCt5d9DXKKLjbSq/MFQ/nwdgfgfJAsgrSXN0I+6fIf8/INtI4YcKTpzAblXdeAkWdVrD4xpRSC7TpEHdEGMWEBtSWzJy8b92F2cxCXuk/QPDK4d8/QuelkFD9C9IztmgSqq7fQQg=
  - secure: ZiTMhiF/+VXkPad7MQWqivnvKI3io2uR3vZRQQhVERmmchMazj0JJ9c2Nwy2WAOI85fS4nWG8vcHU7AY75lddfyR22GV5sDa+oQdAuZGLmzyFjjv3KhvmursZAYxgD8vCx3WiedKBX93SuvYQV4WrBw3zTKfLMDpITRqmG8W9gw=
  - secure: fuSaiDXd3ih216ATs+CwEyFMRr3gFcSdW8ad/kRy+QluBDpcZLhFo0hx3oE44jWgYbkVCSjsMERIL8zclGl395VF1hjTT4rvqsFoZ77MIk/X5iJZ68vxLt0HKnLfrLXCfa4QBMWnYNAb0IlLhSnXcxtxRq79rIfu7o16nEHU0Cw=
before_install:
- sudo apt-get update -qq
install:
- mvn -N -q deploy --settings deploy.xml
script:
- mvn -N test -B
CI_DEPLOY_USERNAME=kristianhermannkarl:
  secure: AaV8ldSF9Llp6TcQpCfzUYlWhP9wNIJd+1MxjLbQzwRUJ7AbhO7Z5rmSLT+llH+AwfNrulvfM2cfo7pov/OcFkQFsj8Kn2B0x3cpHcMRtv/moS5aZFsoNX0zJUww440vX6DLlYL/eoc9Vo9S24LoVav4LuEP02mI2G11xmZCFJE=
