language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master
  - coverity_scan
env:
  global:
  - secure: NleX7IcOJ4Vwt4VLkXskUsHUVHt/tMtSw+l/tKfhievZ6Ddtyo+bgSXaWz9sCysYGKycOik84rerUEXwc4eG5sWavwNYudG7/FfWxvU80Dvbztzjb34TmLSA6bOwcYPKt3UC6Aa9vH1RvMDeITU6ravdxXSr3jpIYqaWAd9h2CI=
  - secure: fETdgm1lQXxABK+pnhOk/YRSjlmpUbv64Fp4TBhE2sGNR0EM6xMkKDWO2WrtXWIgGPLt7EIBujkI4pntPTrp59NSkkuAOLiZtfn3vr25FCuercHq99St9BtSFSksYPUnOpnQTCndIAseeA0jFszoR4Swbv3HjIhD3bH9oTlrzKE=
  - secure: VPbi1UELzFM2vxyjzotBvo+wc6rJBfHrUkY1xca2aPndRsfZZklUZCiFPmcNBF3kD9CCUbhuT4HjeZgWCONaZKYu9Qp3CUneaIn2IbT3ewevC7OD+uxw4K4QuzdnunSPGXWVB3QT4Jqcfv9ehO5bfC0nxmdSppEGguM+1/S9eFmAZvWJSqhJHPZ2SUIS5uNMq5G9h0TuC4HkwADLlJKTrl0BkUcSdbFj5vda6zV2njFKrUE+wgctyuXNIER1YmT7Mk/y2PtCjO9hlPb5ilyBiZkWCOdxPYMOEUcDw9laZoiz2993RQMJeOrOVzDOJlBpEvQ/uxGeShZhirEwNQUe9VeXSle3bZvFzbOho/B9y9Rt1wWKAPXPjp4o3Uhgz/sNNOPnZ1WSUb+K9ZbwuwIq4bF88kDlBZhGenv3HGY/qotBmCkBWMZxcd465qqh62ooIFnYn7xnGky7zWXUhCqkFt2LRxQg2F1TO44ctg2NfI7aWZnVe8w8TiZbUTx46J1nO8JnfPx6RhsuUgHF2+mCNIIOOlQTRNYQaV6atxSnkFNWKvMRV97M6F0yxOPp6SG5TJyeQp3P5vx6xUGdfrj0u7+2910ZxD8Aqo04ijtqb98LDGc0FAAn8NmDx/KPkCzjro8FkWZVfPJhkcI94ztjTFe5qJI71YELV2w1tqUbqP0=
addons:
  hosts:
  - myshorthost
  hostname: myshorthost
  coverity_scan:
    project:
      name: GraphWalker/graphwalker-project
      description: Build submitted via Travis CI
    notification_email: nils.olsson@arcticblue.se
    build_command: mvn clean compile -DskipTests=true
    branch_pattern: coverity_scan
before_install:
- pip install --user codecov
install:
- sudo apt-get update -qq
script:
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then if [ "${TRAVIS_PULL_REQUEST}" = "false"];
  then mvn clean deploy --settings deploy.xml; else mvn clean package; fi fi
after_success:
- codecov
before_deploy:
- export TRAVIS_TAG="LATEST-BUILDS"
- git tag --force "$TRAVIS_TAG" "$TRAVIS_COMMIT"
- git push --force --tags https://${GH_TOKEN}@github.com/GraphWalker/graphwalker-project.git
  > /dev/null 2>&1
deploy:
  provider: releases
  api_key:
    secure: N1NZGwX9/Hrm7Qs3BP4AJ1HnUr7rydL+vd4e9rW6ISs6M6acUShxIMLFsxTXrYblsfDYCQ81r7S4tRENYXjvXwZjQGSyBmkkY1WQuQhl4QV4eepCy5i/yp7m15P7CZHkeqg5XSJteST4rpaz9oxrBCRYyVGArZUlQcWYnpUbmB0=
  tag_name: "$TRAVIS_TAG"
  target_commitish: "$TRAVIS_COMMIT"
  draft: false
  file:
  - graphwalker-cli/target/graphwalker-cli-4.0.0-SNAPSHOT.jar
  - graphwalker-studio/target/graphwalker-studio-4.0.0-SNAPSHOT.jar
  overwrite: true
  skip_cleanup: true
