language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
branches:
  only:
  - master
  - coverity_scan
env:
  global:
  - secure: NleX7IcOJ4Vwt4VLkXskUsHUVHt/tMtSw+l/tKfhievZ6Ddtyo+bgSXaWz9sCysYGKycOik84rerUEXwc4eG5sWavwNYudG7/FfWxvU80Dvbztzjb34TmLSA6bOwcYPKt3UC6Aa9vH1RvMDeITU6ravdxXSr3jpIYqaWAd9h2CI=
  - secure: fETdgm1lQXxABK+pnhOk/YRSjlmpUbv64Fp4TBhE2sGNR0EM6xMkKDWO2WrtXWIgGPLt7EIBujkI4pntPTrp59NSkkuAOLiZtfn3vr25FCuercHq99St9BtSFSksYPUnOpnQTCndIAseeA0jFszoR4Swbv3HjIhD3bH9oTlrzKE=
  - secure: UGWyiUB7ji6bNkCywhexy7sErFE9X4YUgZFiTDBxba+P7Czsipj4NHvXCum3v53n5OO7WJ0WVKRTUXLgVmH5aJW3YhLo7zmoW7zlChD5xxHY55s3EEQzYfWNF9IJURgbzt5TzhPi6RROnOiDoUqKZBY8BepaT/fguWNACuJ5+5g=
addons:
  hosts:
  - myshorthost
  hostname: myshorthost
  coverity_scan:
    project:
      name: GraphWalker/graphwalker-project
      description: Build submitted via Travis CI
    notification_email: nils.olsson@arcticblue.se
    build_command: mvn clean compile -DskipTests=true
    branch_pattern: coverity_scan
before_install:
- pip install --user codecov
install:
- sudo apt-get update -qq
script:
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then if [ "${TRAVIS_PULL_REQUEST}" = "false"]; then mvn clean deploy --settings deploy.xml; else mvn clean package; fi fi
after_success:
- codecov
deploy:
  provider: releases
  api_key:
    secure: U8sf3QpYYWeF872fbOU9gu+Cak9USDFlzfIfdyh7yg1R+jKCdunPZED6Uc0CYA8qmXz5UiaFO5wCdbg97QcniwNp0ei0FqjD7v/2NWQlff4yfMd7OpUNBKjOPk7nQT1xIHxo/gdNr1IBCgTrDKXYfpmre+dxvY9K/SAlNTgwLzHb6RxImN9rXFwA8ejeW74uBqotRgo4iNozwIDhABVntJSi4AtHYTnV99v4l85Z5aU+mfNYX5pw8AGoqYLloIDz/WYE8rJi1I6GFAGdJtrjIlCJzBb+HgxuuwIm9TGvqftIwyu5x14BVA9IsQE5w/Jvtdn1PsxjOzwipGI5KZVQ1v8IaC+wssiXDp9cw0s880o8c3wip+My2r3jy0fwiaVgaYmgThcmM5XXgupi4geAuKMv5ebEnBDYS7o2sKnZwCVdGjaKeJ3mTXMhl8d4ji4PCt0WZ2HIhtm0Eygc4e1GoFDotz41Uv2pAyKRh7ut7hq4Jv6LuV4+YcP7NajvV6nO3B+BaK1XwCXHjmFxJm7q5855/ucfZRzL8CMS7BGjo+70SRK6w7eSTSX3W2Vtichycskp68VllhchjB2FIrw6NgWrHAFmUdTNzMIkwjrL42kyD5qAASECS4/J6s7YO7kpvWnY6jDRMxT1TIojvCB4T9+M+VqnM1H0WLZ8IsNlCg8=
  tag_name: LATEST-BUILDS
  target_commitish: $TRAVIS_COMMIT
  draft: false
  file:
    - "graphwalker-cli/target/graphwalker-cli-4.0.0-SNAPSHOT.jar"
    - "graphwalker-studio/target/graphwalker-studio-4.0.0-SNAPSHOT.jar"
  overwrite: true
  on:
    tags: false
