language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "RebKhouehZV7PgRw0ET02ANDJVafpFo/3GvvPIPiCUYmQXgoX/cTb1EihpZcoiQceDFx0F0TMmTWUjRurGA0+yE8Aex+7ILS0etkLB9eKu0md5hqMLRTlVz/3Cu3MX/pRgseJ5ok/bbuaVWOY86Bdc3zoOmBgoEOH65JUCllN74="
    - secure: "DULEDHg9re1lOZEUn3wEtiFD10A1fABeZzJtph94jrRIBnMS03wQ7f7cDbt8WhgxFhJlZ2zkk4XWf2GN3cxmG1XvD7g/41RRGwFkFjhecsr4rNPITLSwIlN27VyOeoCXKAoK7gACUe+iOeUWKJPzDnkh2/NVrXZtf3vW7yQF90Q="

before_install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh
  - ../graphwalker-project/tools/build.sh

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -q deploy --settings ../graphwalker-project/deploy.xml || false'
