language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "DUmpGo+M1fD2kkIgFuUL0P8BHT6vS3649TDjyIx3oANH8BPuMczaWZkFvLnJVZ0DfUwjKBRWUsVtC7Lfvd2IqX00JpyR0wQtxOTPlL+Xhan8sYSTm76th7zR6zNekgkKofAD1c5eQEG1OI6EhxHYhsQcUu4wBCVdOXk/Y3Vf/RU="
    - secure: "pJTcqB+6G+F8pGd0eL9cnDvFiZOwaHrPMcTVdp8pkhGok5ti5Aw17yxioMEIebN1C1eZeKR6pqF8g9AXXLPLgaZw8WEWeDE1GlQ20t9QB7hS4JpxedRCFb+GUidWjtsGNHO3kYver8A3TXnds5CeG8IbznchNOEbBahey5sIA1s="

install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh

script:
  - ../graphwalker-project/tools/build.sh
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -q deploy --settings ../graphwalker-project/deploy.xml || false'