language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "Yr537my0WtG+Aw0vAmbsYClr5pkuFCFMyVB7yEpQokS/z3rmIfsuPdf1TGa1U6ZmLQtu8qrkzsu+rAUENgALgXbOuCpv5frp+ImH9zL6N2vrHUHpEKevRYV6ZCpehOfKGLNgC/jQ4zttm9lSnq2kdslo4gf0INuvVdbH1imMrdY="
    - secure: "F+dRArOikV+eGZJT6kJ9XmcPeU+Eg/OVOzuk5iWRL8MGEsJV2rT4hObwxkFpdJv0GP3k+u905jRQxH9j2g3z4AyoDrx7TRvzJuJytlJta+bgwj9cKOERuJYPi1IWoUYNFelu2wSZAPZ9sFJVgx6x9TWHQRfrHf6GaVAmJ+1dNus="

before_install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh
  - ../graphwalker-project/tools/build.sh

install:
  - mvn -q deploy --settings ../graphwalker-project/deploy.xml
