language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "AfJjHSpk741KebQ5Itut/M71MjO3GPte12sDzqfrGhUxUFHB49oUroPWeKi3dpTsDowcdSCX1SnecL6oW1NmbfZKM1mPLoOnBvsZ22EbDQK+NMxSv7Wvisjc377lXFxZU55yhLGoi2aJoW5yDNDq2fOSMou1M+UlxrZQGFi176U="
    - secure: "YRG3INo4QLAE1yCB9xRaDO2eEbNpkoRL+fcZM1SKb8CXYBMn5zZi8zzaDNCbbV+YRquJ5HsYJDyA2RTuc2Jd6b0ZwoCHUVKo8hI9/8bl5wa+zzo40rmb21KEoSrQNtQN7OAGPHsSVrPapWpPk4ZDmyHQkhukfOnynxjcftheAj0="

before_install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh
  - ../graphwalker-project/tools/build.sh

install:
  - mvn -q deploy --settings ../graphwalker-project/deploy.xml

after_success:
 - mvn -q package
 - cp target/graphwalker-*.jar target/graphwalker.jar
 - sshpass -p $GW_PASSWORD scp target/graphwalker.jar $GW_USER@graphwalker.org:/var/www/archive
