language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "Si+FksmD04Qev09hkYqWYN4rYQderrvMt6/kZBTgEek/v4Bd8QVCcbkZemYQCLnfhm94fNJDVrvpbrZhkeSWhCXKnnsYMH9oaxQWSd4aUI55V9QAseVAWMod5d2TSD7kTIo1owV5xh9LHTLmwnv4v6WmV3dSHSQc0zQh09dFC/M="
    - secure: "IVcJyf13GCwLkpYKqygwTH9f3EG1YiqdmXWPCt5d9DXKKLjbSq/MFQ/nwdgfgfJAsgrSXN0I+6fIf8/INtI4YcKTpzAblXdeAkWdVrD4xpRSC7TpEHdEGMWEBtSWzJy8b92F2cxCXuk/QPDK4d8/QuelkFD9C9IztmgSqq7fQQg="
    - secure: "fajibrY17s5ih1W91FLTr1J3G10h2ujF7B7T/XgSbbXWds5rhM1KdAbcZhDe4zEizqvloakkmZxfhtBCZpVtQWxW7E6Z7EHzLJph21Q9ncliVE0AagofnSN6brv9FyFLGS8hz2l/OgPonuKyz1WYqSEWRTxcEQpqg9np5rD/kKY="
    - secure: "goLZHAYVDwFEUVfOBKTT50gqYF8HB/4LjtM0YoKzsYz8POZosASdmZ5D7u9FzOX5rwjWlNrP+vG1NLE9hbjGwv54i94my9OpmN2okVJt8VTBtRPQ/PoWJfLEftnKHmfcuA9c8nqyPo81VK4JLW1XhWkU2WKuWdzXhaYhNkqb9Tw="

before_install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh
  - ../graphwalker-project/tools/build.sh

install:
  - mvn -q deploy --settings ../graphwalker-project/deploy.xml
