language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "dD1GZpf+iFKIcWhGQx0PGwuCak+TgV/TF8TtdtPdUVz5bDpzMQYfaC74DyJa+80hyyxzvf0454SasC9omgJbYPA45JQ05FBq53WIxmX8Qh7y417PmWKof3GwYqKrEKceySCsrJow/CJ5jwCmlbmFZbkToOkjqhD/cwf5BpDS+ns="
    - secure: "nQ/NFJbhcfLXR8AVeZW7d0RwQ3FqpQSaBpPAiTp6qxqeU3Ahbpc7g63fpCs7742cymtvH4S1Q/yVTXRIXs4KA0FqKqRW+MFH4QO8wcKL/sPqqI8wbO3o75Q3ENJInJ2DOpwMf3/pThGeOY6JVPvVMsrtsI9k58n/nwLOsVQhi3E="

install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh

script:
  - ../graphwalker-project/tools/build.sh
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -q deploy --settings ../graphwalker-project/deploy.xml || false'
